image: ruby:3.2

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby
    - public 
    - .jekyll-metadata 

before_script:
  - bundle install -j $(nproc) --path vendor


pages:
  stage: deploy
  script:
  - bundle exec jekyll build --incremental --trace -d public
  artifacts:
    paths:
    - public
  only:
  - main
